const  Connect  = require ( "./server/helper/db/connect")
const  Peliculas  = require ( "./server/model/peliculaModel")
const  Funciones  = require ( "./server/model/funcionModel" )
const  Clientes  = require ( "./server/model/userModel")
const  Boletas  = require ( "./server/model/boletaModel")
const { ObjectId } = require ( "mongodb")